### ISSUE TITLE
Can't sign messages when there is a space in the URL

### ISSUE THREAD

**Issue by vinhboy** [winebarrel/faraday_middleware-aws-signers-v4#1]
I am trying to use this gem to sign some requests to AWS ElasticSearch Service, the urls are like this:

```
https://xxxx.us-east-1.es.amazonaws.com/items/item/_search?q=item+one
```

The `+` is a url encoded space.

This gem can't properly sign that request and is returning

```
The request signature we calculated does not match the signature you provided.
```

Requests to URLs without the space works...

```
https://xxxx.us-east-1.es.amazonaws.com/items/item/_search?q=item
```

I am trying to figure this out, but if you have a solution, let me know. Thanks!

Here is the failing code (you'll have to put up your own IAM protected elasticsearch instance to test):

```
require 'faraday_middleware'
require 'faraday_middleware/aws_signers_v4'
require 'pp'

conn = Faraday.new(url: 'https://xxx.us-east-1.es.amazonaws.com') do |faraday|
  faraday.request :aws_signers_v4,
    credentials: Aws::Credentials.new('XXXX', 'XXXX'),
    service_name: 'es',
    region: 'us-east-1'

  faraday.response :logger
  faraday.response :json, :content_type => /\bjson$/
  faraday.response :raise_error

  faraday.adapter Faraday.default_adapter
end

res = conn.get '/items/item/_search?q=item+one'
pp res.body
```

**Comment by vinhboy** [comment]
I dug around the aws-sdk code a bit, and I found that they actually have a method specifically for converting `+` into `%2B`

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/seahorse/util.rb#L23

Maybe this should be incorporated into the gem some how.

**Comment by winebarrel** [comment]
Do you use the `faraday.request  :url_encoded` ?

**Comment by vinhboy** [comment]
Fixed in https://github.com/winebarrel/faraday_middleware-aws-signers-v4/releases/tag/0.1.4
