### ISSUE TITLE
Faraday Middleware SigV4 shouldn't request compressed content

### ISSUE THREAD

**Issue by dinusX** [winebarrel/faraday_middleware-aws-signers-v4#13]
The goal of this plugin is to just add SigV4 support to faraday middleware.
However this plugin also adds code that asks for compressed content, but doesn't add support for decompressing content.

Code:
https://github.com/winebarrel/faraday_middleware-aws-signers-v4/blob/588b8c1086a72e2762ea3834bfff3d9f71b66024/lib/faraday_middleware/request/aws_signers_v4.rb#L69-L71

We should remove this code and leave the flexibility to the users to configure compression as they need.

**Comment by dinusX** [comment]
Related issue: https://github.com/elastic/elasticsearch-ruby/issues/457

**Comment by winebarrel** [comment]
the net/http library modifies the header regardless of this library.
see https://github.com/ruby/ruby/blob/c08f7b80889b531865e74bc5f573df8fa27f2088/test/net/http/test_http_request.rb#L20

If you want to remove `accept: gzip`, please use an adapter other than `net/http`.

**Comment by winebarrel** [comment]
I'm sorry.
With the combination of `net/http`and `faraday_middleware-aws-signers-v4`, the automatic decompression function of `net/http` may be disabled.

Please try v.0.1.9.

Thanks for your issue.
