### ISSUE TITLE
Do you have down graded version for ruby 1.8.7?

### ISSUE THREAD

**Issue by santhoshcd** [winebarrel/faraday_middleware-aws-signers-v4#16]
Hi
    We are planing to migrate search engine service from Elasticsearch to AWS elasticsearch as a Service and trying to connect AWS ES using aws signers v4 gem ( with elasticsearch) in Rails app.
But we are not to install this gem in rails (2.3.2) app to sign the request.

We have monolithic app
```
rails 2.3.2 
ruby 1.8.7
elasticsearch 6.0
```

Question?
1. Are you supporting this gem for ruby 1.8.7? 
     if not,  do you have any other alternate approaches or down graded version for ruby 1.8.7?

**Comment by winebarrel** [comment]
> 1. Are you supporting this gem for ruby 1.8.7?

No.

> if not, do you have any other alternate approaches or down graded version for ruby 1.8.7?

um.. I can not think of a good approach.
`faraday_middleware-aws-signers-v4` is a small library,  so I can fix it.
However I do not know if dependent libraries are compatible with 1.8.7 (e.g. `faraday`)
