### ISSUE TITLE
Migrate to use aws-sdk-v3

### ISSUE THREAD

**Issue by cosmo0920** [winebarrel/faraday_middleware-aws-signers-v4#17]
Originally reported in https://github.com/elastic/elasticsearch-ruby/issues/486.

Currently, faraday_middleware/aws_signers_v4 requires aws-sdk v2.
Latest aws-sdk version is v3.
Could you bump up dependent aws-sdk version?

**Comment by winebarrel** [comment]
> Could you bump up dependent aws-sdk version?

I'm sorry. I will not bump up dependent aws-sdk version.
Because library interface is different between v2 and v3 ...

I want you to use [faraday_middleware-aws-sigv4](https://github.com/winebarrel/faraday_middleware-aws-sigv4)  if you want to bump up aws-sdk version.

**Comment by cosmo0920** [comment]
OK. Thank you for your answer.
