### ISSUE TITLE
Version that supports aws-sdk-v1

### ISSUE THREAD

**Issue by buffym** [winebarrel/faraday_middleware-aws-signers-v4#4]
We have an older rails application that still uses aws-sdk-v1, but we need to sign aws version 4 requests (for elasticsearch), and can't upgrade to aws-sdk-v2 yet. I've made a version of this gem that works with aws-sdk-v1 1.66.0. It is here: https://github.com/buffym/faraday_middleware-aws-signers-v4 with the tag vaws-sdk-v1. I wonder if you think it would be worthwhile to put some conditionals in this gem to handle either version of the aws sdk? I'm happy to do that if you're interested. If not, I may just create a new GEM borrowing heavily from this that will support v1. Thanks for the work on this - it has been a lifesaver!

**Comment by winebarrel** [comment]
This library does not support aws-sdk-v1. I'm sorry

**Comment by trose89** [comment]
@buffym You can support aws-sdk-v1 and v2 by including aws-sdk-resources (v2) as well. I'll submit a pull request to change this to require the aws-sdk-resources library. We have a similar situation where we have some libraries dependent on v1 but we'd like to use this middleware
