### ISSUE TITLE
'prepend' only avail in ruby 2.0 and breaks 1.9

### ISSUE THREAD

**Issue by aabes** [winebarrel/faraday_middleware-aws-signers-v4#5]
This commit switched the override approach to using Ruby 2.0 Prepend
https://github.com/winebarrel/faraday_middleware-aws-signers-v4/commit/ff491c5d8700cf91741aa108e9f3d885fcac9e25

Also, could it be that the downcase is not required anymore? ( I haven't fully dug into the code path, but it seems that aws-sdk-core v4 signer does already downcase? https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/signers/v4.rb#L184

)

**Comment by stephencattaneo** [comment]
I'm about to fork this repo to revert ff491c5 for my own organization.  Looking at the other forks of this repo about half are doing the same.  Please consider removing ff491c5 (I can open PR if you'd like).

**Comment by winebarrel** [comment]
This library does not support Ruby 1.9. I'm sorry.
