### ISSUE TITLE
support for aws sdk v3

### ISSUE THREAD

**Issue by JuanLUJoanne** [winebarrel/faraday_middleware-aws-signers-v4#9]
https://github.com/winebarrel/faraday_middleware-aws-signers-v4/blob/6593b9932fb7251720a672111d8a6620b155418c/faraday_middleware-aws-signers-v4.gemspec#L19

Hi, 

i am currently using your gem for our app. 
Now I need to use aws-sdk (~> 3.0.0.rc9)  for the other gem's dependency.
So i got conflicts now:
`bundle install
Fetching gem metadata from https://rails-assets.org/..
Fetching version metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.....
Bundler could not find compatible versions for gem "aws-sdk-resources":
  In snapshot (Gemfile.lock):
    aws-sdk-resources (= 2.10.24)

  In Gemfile:
    aws-sdk (~> 3.0.0.rc9) was resolved to 3.0.0.rc9, which depends on
      aws-sdk-resources (= 3.0.0.rc2)

    faraday_middleware-aws-signers-v4 was resolved to 0.1.7, which depends on
      aws-sdk-resources (~> 2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`
Could you please make your gemspec support to aws-sdk (~> 3.0.0.rc9) ?
by 

`spec.add_dependency 'aws-sdk-resources', '~> 2.10'`
Thank you in advance.

**Comment by winebarrel** [comment]
Currently, I am developing a new gem for aws-sdk-v3.
This gem does not support aws-sdk-v3.
see https://github.com/winebarrel/faraday_middleware-aws-sigv4

Please use v0.1.8 If you use aws-sdk-v2.
